"""F5-TTS voice provider.

F5-TTS is an external tool that the user runs independently.  This provider
does NOT generate audio directly.  Instead, its ``generate()`` method triggers
the narration-package export workflow:

    generate-voice (f5tts mode)
        └─→ F5ExportService.export(project_id, script)
                └─→ <project>/f5_package/narration_pack.json
                └─→ <project>/f5_package/scene_1.txt … scene_N.txt
                └─→ ZIP returned via /export-f5-package endpoint

The user then runs F5-TTS externally and uploads the resulting WAV/MP3 files
via the ``/import-f5-audio`` endpoint, which triggers
:class:`~services.voice.importer.F5ImportService`.
"""

from __future__ import annotations

from typing import List

from models.schemas import SceneVoiceResult, ScriptSchema
from services.voice.exporter import F5ExportService
from services.voice.providers.base import VoiceProvider
from utils.file_manager import save_json, load_json, project_dir


class F5TTSProvider(VoiceProvider):
    """Voice provider that exports a narration package for F5-TTS processing.

    Audio is NOT generated by this provider.  It signals to the pipeline that
    narration audio will be supplied via the import workflow.
    """

    name: str = "f5tts"

    async def generate(
        self,
        project_id: str,
        script: ScriptSchema,
        voice: str,
    ) -> List[SceneVoiceResult]:
        """Export narration text package for external F5-TTS processing.

        Calls :class:`F5ExportService` to create the ``f5_package/`` directory
        structure under the project folder, then updates project metadata.

        Args:
            project_id: Unique project identifier.
            script: Full script with scene narrations to export.
            voice: Ignored for F5-TTS (voice model selection is external).

        Returns:
            Empty list — audio does not exist yet.  The render pipeline will
            check ``voice_generation_status`` and block rendering until audio
            has been imported via ``/import-f5-audio``.
        """
        exporter = F5ExportService()
        exporter.export(project_id, script)

        # Trigger Google Drive Queue Auto-Enqueue (Phase-2)
        from services.f5_queue_service import F5QueueService
        queue_service = F5QueueService()
        queue_service.enqueue_project(project_id)

        # Update project status flags.
        cfg = load_json(project_id, "config.json") or {}
        cfg["voice_generation_status"] = "pending"
        cfg["f5_package_exported"] = True
        save_json(project_id, "config.json", cfg)

        return []
