"""F5 Completion Watcher Service.

Periodically scans the Google Drive completed folder for audio files generated by Colab,
imports them using F5ImportService, and handles recovery of stuck projects.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import shutil
import time
import zipfile
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from typing import Optional

from config import settings
from services.voice.importer import F5ImportService, ImportValidationError
from utils.file_manager import load_json, save_json, project_dir

logger = logging.getLogger("f5_watcher")


class F5CompletionWatcher:
    """Watches Google Drive folders for completed and stuck F5-TTS projects."""

    def __init__(self) -> None:
        self.importer = F5ImportService()
        self.is_running = False
        self.warned_skipped_projects: set[str] = set()

    async def start(self) -> None:
        """Start the background watcher loop."""
        if self.is_running:
            return
        self.is_running = True
        logger.info("[F5_WATCHER] Starting F5 completion watcher task.")
        
        # Run stuck project recovery on startup (refinement #5)
        try:
            self.recover_stuck_projects()
        except Exception as e:
            logger.error(f"[F5_RECOVERY] Error during startup recovery: {e}", exc_info=True)

        # Start the polling loop
        asyncio.create_task(self._loop())

    async def _loop(self) -> None:
        """Periodic polling loop (runs every 30 seconds - refinement #4)."""
        while self.is_running:
            try:
                await self.scan_and_process()
            except Exception as e:
                logger.error(f"[F5_WATCHER] Error during scan cycle: {e}", exc_info=True)

            try:
                self.cleanup_completed_projects()
            except Exception as e:
                logger.error(f"[F5_CLEANUP] Error during completed projects cleanup: {e}", exc_info=True)

            await asyncio.sleep(30)

    def stop(self) -> None:
        """Stop the background watcher loop."""
        self.is_running = False
        logger.info("[F5_WATCHER] Stopped completion watcher.")

    async def scan_and_process(self) -> None:
        """Scan the completed folder on Google Drive and import finished projects."""
        completed_dir = settings.f5_completed_path
        if not completed_dir.exists():
            logger.warning(f"[F5_WATCHER] Completed folder does not exist at {completed_dir}")
            return

        # Scan for project folders
        for path in completed_dir.iterdir():
            if not path.is_dir():
                continue

            folder_name = path.name
            match = re.match(r"^project_([a-zA-Z0-9_-]+)$", folder_name)
            if not match:
                # Skip folders that do not match the expected naming pattern
                continue

            project_id = match.group(1)

            try:
                await self._process_completed_folder(project_id, path)
            except Exception as e:
                logger.error(
                    f"[F5_WATCHER] Failed to process project {project_id} in completed folder: {e}",
                    exc_info=True
                )

    async def _process_completed_folder(self, project_id: str, path: Path) -> None:
        """Process a detected project folder in the completed directory.

        Args:
            project_id: Unique project identifier.
            path: Directory path in the completed folder on Drive.
        """
        # Verify project exists locally
        local_cfg = load_json(project_id, "config.json")
        if not local_cfg:
            if project_id not in self.warned_skipped_projects:
                logger.warning(f"[F5_WATCHER] Project {project_id} found on Drive completed folder but not found locally. Skipping.")
                self.warned_skipped_projects.add(project_id)
            return

        # 1. Import duplicate protection (refinement #7)
        # Skip if f5_processing_status is already "audio_ready" or "completed"
        current_status = local_cfg.get("f5_processing_status")
        voice_status = local_cfg.get("voice_generation_status")
        if current_status in ("audio_ready", "completed") or voice_status == "completed":
            logger.info(f"[F5_IMPORT] Project already imported.")
            return

        logger.info(f"[F5_WATCHER] Completed project detected {project_id}")

        # 2. Read and parse status.json
        status_file = path / "status.json"
        if not status_file.exists():
            logger.error(f"[F5_WATCHER] Missing status.json for project {project_id} in completed folder.")
            self._mark_project_failed(project_id, path, "Missing status.json in completed folder")
            return

        try:
            with open(status_file, "r", encoding="utf-8") as f:
                status_data = json.load(f)
        except Exception as e:
            logger.error(f"[F5_WATCHER] Corrupt status.json for project {project_id}: {e}")
            self._mark_project_failed(project_id, path, f"Corrupt status.json: {e}")
            return

        # Validate status is "completed"
        status = status_data.get("status")
        if status != "completed":
            logger.warning(f"[F5_WATCHER] Status in status.json for project {project_id} is '{status}' (expected 'completed').")
            if status == "failed":
                self._mark_project_failed(project_id, path, "Colab worker reported failure")
            return

        # 3. Scene count validation (refinement #1)
        expected_scene_count = status_data.get("scene_count")
        if expected_scene_count is None:
            logger.error(f"[F5_WATCHER] status.json missing scene_count field for project {project_id}")
            self._mark_project_failed(project_id, path, "Missing scene_count in status.json")
            return

        # Collect audio files matching scene_*.wav or scene_*.mp3
        audio_files = []
        for file_path in path.iterdir():
            if file_path.is_file() and file_path.suffix.lower() in (".wav", ".mp3"):
                if re.match(r"^scene_\d+\.(wav|mp3)$", file_path.name, re.IGNORECASE):
                    audio_files.append(file_path)

        actual_scene_count = len(audio_files)
        if actual_scene_count != expected_scene_count:
            logger.error(
                f"[F5_WATCHER] Scene count mismatch for project {project_id}: "
                f"expected {expected_scene_count}, found {actual_scene_count} files."
            )
            self._mark_project_failed(
                project_id,
                path,
                f"Scene count mismatch: expected {expected_scene_count}, found {actual_scene_count} files"
            )
            return

        # 4. Package audio files + status.json into in-memory ZIP
        zip_buf = BytesIO()
        with zipfile.ZipFile(zip_buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for audio_path in audio_files:
                zf.write(audio_path, arcname=audio_path.name)
            # Also include status.json in ZIP to allow internal validation in F5ImportService
            zf.write(status_file, arcname="status.json")
        zip_bytes = zip_buf.getvalue()

        # 5. Trigger F5ImportService to import audio
        try:
            self.importer.import_audio(
                project_id=project_id,
                zip_bytes=zip_bytes,
                script=None  # Fallback to narration_pack.json count validation
            )
            logger.info(f"[F5_IMPORT] Audio imported successfully {project_id}")
        except ImportValidationError as e:
            logger.error(f"[F5_IMPORT] Validation failed during import for project {project_id}: {e}")
            self._mark_project_failed(project_id, path, f"Import validation error: {e}")
            return
        except Exception as e:
            logger.error(f"[F5_IMPORT] Unexpected error importing project {project_id}: {e}")
            self._mark_project_failed(project_id, path, f"Import exception: {e}")
            return

        # 6. Update local config status
        cfg = load_json(project_id, "config.json") or {}
        cfg["f5_processing_status"] = "audio_ready"
        cfg["f5_last_update"] = datetime.now(timezone.utc).isoformat()
        save_json(project_id, "config.json", cfg)

    def recover_stuck_projects(self) -> None:
        """Scan processing folder and move projects stuck for >12 hours to failed (refinement #5)."""
        processing_dir = settings.f5_processing_path
        if not processing_dir.exists():
            return

        logger.info("[F5_RECOVERY] Scanning for stuck projects...")
        now = time.time()
        stuck_threshold_seconds = 12 * 3600  # 12 hours

        for path in processing_dir.iterdir():
            if not path.is_dir():
                continue

            folder_name = path.name
            match = re.match(r"^project_([a-zA-Z0-9_-]+)$", folder_name)
            if not match:
                continue

            project_id = match.group(1)

            # Determine age of the folder
            status_file = path / "status.json"
            mtime = status_file.stat().st_mtime if status_file.exists() else path.stat().st_mtime
            age_seconds = now - mtime

            # Double check with local config update timestamp
            local_cfg = load_json(project_id, "config.json")
            if local_cfg:
                last_update_str = local_cfg.get("f5_last_update")
                if last_update_str:
                    try:
                        last_update = datetime.fromisoformat(last_update_str)
                        cfg_age = (datetime.now(timezone.utc) - last_update).total_seconds()
                        age_seconds = max(age_seconds, cfg_age)
                    except (ValueError, TypeError):
                        pass

            # Worker ownership tracking (refinement #1)
            worker_name = "unknown"
            worker_file = path / "worker.json"
            if worker_file.exists():
                try:
                    with open(worker_file, "r", encoding="utf-8") as f:
                        worker_data = json.load(f)
                        worker_name = worker_data.get("worker", "unknown")
                except Exception:
                    pass

            if age_seconds > stuck_threshold_seconds:
                logger.warning(
                    f"[F5_RECOVERY] Stuck project detected: {project_id}. "
                    f"Processing for {age_seconds / 3600:.1f} hours. Moving to failed."
                )
                self._mark_project_failed(
                    project_id,
                    path,
                    f"Processing timed out after {age_seconds / 3600:.1f} hours",
                    worker_name=worker_name
                )

    def _mark_project_failed(self, project_id: str, current_drive_path: Path, reason: str, worker_name: str = "unknown") -> None:
        """Marks a project as failed locally and moves its drive folder to the failed directory.

        Args:
            project_id: Project identifier.
            current_drive_path: Current folder path on Google Drive (e.g. completed/project_id).
            reason: Log reason for failure.
            worker_name: The worker processing this project.
        """
        failed_dir = settings.f5_failed_path
        try:
            failed_dir.mkdir(parents=True, exist_ok=True)
            dest_path = failed_dir / current_drive_path.name

            # Clean destination if it exists
            if dest_path.exists():
                shutil.rmtree(dest_path)

            shutil.move(str(current_drive_path), str(dest_path))

            # Write a failed status.json in the failed folder on Drive
            failed_status_file = dest_path / "status.json"
            failed_status_data = {
                "project_id": project_id,
                "status": "failed",
                "reason": reason,
                "worker": worker_name,
                "failed_at": datetime.now(timezone.utc).isoformat()
            }
            with open(failed_status_file, "w", encoding="utf-8") as f:
                json.dump(failed_status_data, f, indent=2)

            logger.warning(f"[F5_RECOVERY] Project {project_id} failed while owned by worker {worker_name}")
        except Exception as e:
            logger.error(f"[F5_WATCHER] Failed to move project {project_id} to failed directory: {e}")

        # Update local config
        cfg = load_json(project_id, "config.json") or {}
        cfg["f5_processing_status"] = "failed"
        cfg["f5_last_update"] = datetime.now(timezone.utc).isoformat()
        cfg["f5_failure_reason"] = reason
        cfg["f5_failed_worker"] = worker_name
        save_json(project_id, "config.json", cfg)

    def cleanup_completed_projects(self) -> None:
        """Deletes completed projects from Google Drive if older than completed_cleanup_days (Phase-2 refinement)."""
        completed_dir = settings.f5_completed_path
        if not completed_dir.exists():
            return

        now = datetime.now(timezone.utc)
        cleanup_days = settings.completed_cleanup_days
        cleanup_threshold_seconds = cleanup_days * 24 * 3600

        for path in completed_dir.iterdir():
            if not path.is_dir():
                continue

            folder_name = path.name
            match = re.match(r"^project_([a-zA-Z0-9_-]+)$", folder_name)
            if not match:
                continue

            project_id = match.group(1)

            # Load status.json to check age
            status_file = path / "status.json"
            if not status_file.exists():
                continue

            try:
                with open(status_file, "r", encoding="utf-8") as f:
                    status_data = json.load(f)
            except Exception:
                continue

            # Extract processing_completed_at or generated_at
            completed_at_str = status_data.get("processing_completed_at") or status_data.get("generated_at")
            if not completed_at_str:
                continue

            try:
                completed_at = datetime.fromisoformat(completed_at_str)
                # Parse timezone if missing
                if completed_at.tzinfo is None:
                    completed_at = completed_at.replace(tzinfo=timezone.utc)
                age_seconds = (now - completed_at).total_seconds()
            except (ValueError, TypeError):
                continue

            if age_seconds > cleanup_threshold_seconds:
                # SAFETY REQUIREMENTS: Verify that the project was successfully imported
                local_cfg = load_json(project_id, "config.json")
                if not local_cfg:
                    continue

                local_status = local_cfg.get("f5_processing_status")
                local_voice_results = project_dir(project_id) / "voice_results.json"

                if (local_status in ("audio_ready", "completed")) and local_voice_results.exists():
                    try:
                        shutil.rmtree(path)
                        # Log deletion matching requirement format
                        logger.info(f"[F5_CLEANUP] Removed completed project {project_id} (age: {int(age_seconds / (24 * 3600))} days)")
                    except Exception as e:
                        logger.error(f"[F5_CLEANUP] Failed to delete completed folder {path}: {e}")
