from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class PipelineStep(str, Enum):
    PENDING = "pending"
    SCRIPT = "script"
    SCENES = "scenes"
    SVG = "svg"
    VOICE = "voice"
    VOICE_EXPORTED = "voice_exported"     # F5-TTS: narration pack exported, awaiting audio
    VOICE_IMPORTED = "voice_imported"     # F5-TTS: audio imported, ready to render
    AVATAR = "avatar"
    AVATAR_EXPORTED = "avatar_exported"   # SadTalker: package exported, awaiting clips
    AVATAR_IMPORTED = "avatar_imported"   # SadTalker: clips imported, ready to render
    TIMELINE = "timeline"
    RENDER = "render"
    COMPLETE = "complete"
    ERROR = "error"


class GenerateScriptRequest(BaseModel):
    topic: str
    duration: int = 60
    style: str = "whiteboard"
    voice: str = "male"
    language: str = "english"
    voice_provider: str = "edge"          # edge | f5tts
    avatar_provider: Optional[str] = None # future: liveportrait | musetalk | sadtalker
    # Educational level — adapts vocabulary, depth, analogy sophistication
    # Choices: middle_school | high_school | college | competitive_exam
    educational_level: str = "high_school"


class GenerateScenesRequest(BaseModel):
    project_id: str


class GenerateSvgRequest(BaseModel):
    project_id: str


class GenerateVoiceRequest(BaseModel):
    project_id: str


class GenerateAvatarRequest(BaseModel):
    project_id: str
    # Optional: override the source image path stored in config.
    # If omitted, the path from config.json::avatar_source is used.
    avatar_source: Optional[str] = None


class RenderVideoRequest(BaseModel):
    project_id: str


class SceneSchema(BaseModel):
    scene_id: int
    narration: str
    visual_description: str
    keywords: List[str] = Field(default_factory=list)
    duration: float = 8.0
    # Educational scene role — used by visual planner for intent-aware layout
    # HOOK | INTUITION | EXPLANATION | EXAMPLE | VISUALIZATION | COMPARISON |
    # CAUSE_EFFECT | FORMULA | SUMMARY | REAL_WORLD_APPLICATION
    scene_type: Optional[str] = None
    # Natural bridging phrase spoken at the end to connect to the next scene
    transition_phrase: Optional[str] = None


class LessonPlan(BaseModel):
    """Lightweight pre-script educational structure generated by the lesson planner.

    Guides script generation with learning objectives, optimal scene sequence,
    concept complexity estimate, and curated real-world example suggestions.
    All fields are optional so that fallback defaults work gracefully.
    """
    learning_objectives: List[str] = Field(default_factory=list)
    # Ordered list of scene_type values defining the teaching arc
    scene_sequence: List[str] = Field(default_factory=list)
    # Complexity drives scene count: simple=5-6, medium=7-9, complex=10-12
    concept_complexity: str = "medium"
    estimated_scene_count: int = 6
    recommended_examples: List[str] = Field(default_factory=list)
    domain: str = ""
    # Optional quality feedback injected on rewrite passes
    quality_feedback: List[str] = Field(default_factory=list)
    # Phase 3 additions:
    common_misconceptions: List[str] = Field(default_factory=list)
    prerequisites: List[str] = Field(default_factory=list)
    attention_profile: str = "high_school"


class ScriptQualityReview(BaseModel):
    """Auto-evaluated narration quality metrics produced after script generation.

    Scores are 0.0–1.0. Saved to script_quality_review.json for audit and debugging.
    """
    curiosity_score: float = 0.0  # Kept for backward compatibility
    student_friendliness_score: float = 0.0  # Kept for backward compatibility
    
    # 11 pedagogical dimensions (Phase 3)
    engagement_score: float = 0.0
    clarity_score: float = 0.0
    analogy_usage_score: float = 0.0
    educational_depth_score: float = 0.0
    transition_quality_score: float = 0.0
    real_world_relevance_score: float = 0.0
    misconception_handling_score: float = 0.0
    visual_synchronization_score: float = 0.0
    narrative_variety_score: float = 0.0
    coverage_score: float = 0.0
    human_naturalness_score: float = 0.0
    
    overall_score: float = 0.0
    needs_rewrite: bool = False
    rewrite_reasons: List[str] = Field(default_factory=list)
    
    # Nested structured feedback mapping: dimension -> {"rating": "...", "reason": "..."}
    structured_feedback: Dict[str, Dict[str, str]] = Field(default_factory=dict)


class ScriptSchema(BaseModel):
    title: str
    total_duration: float
    scenes: List[SceneSchema]


class Position(BaseModel):
    x: float
    y: float


class Size(BaseModel):
    w: float
    h: float


class Point(BaseModel):
    x: float
    y: float


class RequiredVisual(BaseModel):
    concept: str
    keywords: List[str] = Field(default_factory=list)
    importance: str = "secondary"  # primary | secondary
    action: Optional[str] = None
    related_to: List[str] = Field(default_factory=list)
    relationship: Optional[str] = None
    animation_intent: Optional[str] = None


class VisualConnection(BaseModel):
    from_concept: str = Field(..., alias="from")
    to_concept: str = Field(..., alias="to")

    class Config:
        populate_by_name = True


class SemanticScenePlan(BaseModel):
    scene_id: int
    topic: str = ""
    headline: str = ""
    layout_type: str = "flow_diagram"
    required_visuals: List[RequiredVisual] = Field(default_factory=list)
    connections: List[VisualConnection] = Field(default_factory=list)
    animation_style: str = "whiteboard_draw"
    camera: Optional[Dict[str, float]] = None
    nodes: List[str] = Field(default_factory=list)
    edges: List[Dict[str, Any]] = Field(default_factory=list)


class RetrievedAsset(BaseModel):
    concept: str
    asset_id: str
    library_path: str
    score: float = 0.0
    fallback: bool = False
    approved: bool = True
    rejection_reason: Optional[str] = None


class VisualAuditEntry(BaseModel):
    scene_id: int
    concept: str
    asset_id: str
    library_path: str
    score: float
    fallback: bool = False
    approved: bool = True
    rejection_reason: Optional[str] = None
    action: Optional[str] = None
    motion_profile: Optional[str] = None
    action_executed: bool = False


class SceneElement(BaseModel):
    id: str
    type: str  # svg, image, arrow, text, label, highlight
    concept: Optional[str] = None
    asset_id: Optional[str] = None
    shape: Optional[str] = None  # deprecated for educational visuals
    position: Optional[Position] = None
    size: Optional[Size] = None
    from_point: Optional[Point] = Field(None, alias="from")
    to_point: Optional[Point] = Field(None, alias="to")
    animation: str = "stroke_reveal"
    delay: float = 0.0
    duration: float = 2.0
    label: Optional[str] = None
    text: Optional[str] = None
    color: str = "#1a1a2e"
    svg_path: Optional[str] = None
    image_path: Optional[str] = None
    stroke_data_path: Optional[str] = None
    asset_library_path: Optional[str] = None
    action: Optional[str] = None
    animation_intent: Optional[str] = None
    motion_profile: Optional[str] = None
    target_id: Optional[str] = None

    @field_validator("from_point", "to_point", mode="before")
    @classmethod
    def _coerce_point(cls, v):
        if v is None:
            return v
        if isinstance(v, Point):
            return v
        if isinstance(v, Position):
            return Point(x=v.x, y=v.y)
        if isinstance(v, dict):
            return Point.model_validate(v)
        return v

    class Config:
        populate_by_name = True


class ScenePlanSchema(BaseModel):
    scene_id: int
    background: str = "white"
    camera: Optional[Dict[str, float]] = None
    elements: List[SceneElement] = Field(default_factory=list)


class WordTimestamp(BaseModel):
    word: str
    start: float
    end: float


class SceneVoiceResult(BaseModel):
    scene_id: int
    audio_path: str
    duration: float
    timestamps: List[WordTimestamp] = Field(default_factory=list)
    # Provider that generated this audio ("edge" | "f5tts").  Populated at
    # generation / import time for traceability.  Defaults to "edge" so that
    # existing serialised voice_results.json files remain valid.
    provider: str = "edge"


class AvatarQuality(str, Enum):
    FAST = "fast"
    STANDARD = "standard"
    HIGH = "high"


class AvatarProviderCapabilities(BaseModel):
    supports_transparency: bool
    supports_live_generation: bool
    supports_high_quality: bool


class AvatarResult(BaseModel):
    """Project-level avatar clip metadata (single video for the whole project).

    P1: SadTalker generates ONE avatar.webm per project (driven by combined.wav).
    The renderer uses scene start-frame offsets to show the correct window of
    the single clip for each scene — no per-scene clips needed.
    """
    avatar_schema_version: int = 1          # Refinement A
    # Relative path to the transparent WebM inside the project directory.
    clip_path: str                          # e.g. "avatars/avatar.webm"
    total_duration: float                   # probed duration of the video clip
    audio_duration: float = 0.0             # probed duration of combined.wav (P2 validation)
    duration_valid: bool = True             # False if drift > tolerance (P2)
    duration_drift: float = 0.0            # abs(audio - video) seconds
    provider: str = "sadtalker"
    provider_version: str = "sadtalker_v1"  # P4 versioning
    manifest_version: int = 1               # P4 manifest version
    cache_key: Optional[str] = None         # P6 SHA256 cache key
    layout: str = "pip"                     # P10 layout mode
    
    # New diagnostic/observability fields (Refinement C)
    background_removed: bool = True
    cache_hit: bool = False
    generation_time_seconds: Optional[float] = None
    validation_passed: bool = True


# Backward-compatibility alias — existing code that imports AvatarSceneResult will still work.
AvatarSceneResult = AvatarResult


class SubtitleEntry(BaseModel):
    text: str
    start_frame: int
    end_frame: int
    highlight_words: List[str] = Field(default_factory=list)


class RenderElement(BaseModel):
    id: str
    type: str
    shape: Optional[str] = None
    position: Optional[Position] = None
    size: Optional[Size] = None
    from_point: Optional[Point] = Field(None, alias="from")
    to_point: Optional[Point] = Field(None, alias="to")
    animation: str = "stroke_reveal"
    start_frame: int = 0
    end_frame: int = 60
    label: Optional[str] = None
    text: Optional[str] = None
    color: str = "#1a1a2e"
    svg_content: Optional[str] = None
    svg_path: Optional[str] = None
    image_src: Optional[str] = None
    stroke_data: Optional[dict] = None
    ink_image_src: Optional[str] = None
    concept: Optional[str] = None
    asset_id: Optional[str] = None
    action: Optional[str] = None
    animation_intent: Optional[str] = None
    motion_profile: Optional[str] = None
    target_id: Optional[str] = None

    @field_validator("from_point", "to_point", mode="before")
    @classmethod
    def _coerce_point(cls, v):
        if v is None:
            return v
        if isinstance(v, Point):
            return v
        if isinstance(v, Position):
            return Point(x=v.x, y=v.y)
        return Point.model_validate(v) if isinstance(v, dict) else v

    class Config:
        populate_by_name = True


class RenderScene(BaseModel):
    scene_id: int
    start_frame: int
    duration_frames: int
    audio: Optional[str] = None
    narration: str = ""
    subtitles: List[SubtitleEntry] = Field(default_factory=list)
    elements: List[RenderElement] = Field(default_factory=list)
    camera: Optional[Dict[str, float]] = None
    # P1: per-scene offset (frames) into the single project avatar clip
    avatar_start_frame: Optional[int] = None


class RenderManifest(BaseModel):
    title: str
    fps: int = 30
    width: int = 1920
    height: int = 1080
    total_frames: int
    scenes: List[RenderScene]
    # P1/P10: Single avatar clip metadata for the whole project (optional)
    avatar_clip_src: Optional[str] = None          # staticFile() path to avatar.webm
    avatar_position: Optional[str] = "bottom_right"  # bottom_right | bottom_left | bottom_center
    avatar_scale: Optional[float] = 0.25           # 0.0–1.0 of video height
    avatar_layout: Optional[str] = "pip"           # P10: pip | teacher_mode | split_screen | full_avatar
    avatar_duration_valid: Optional[bool] = None   # P2 validation result


class JobStatus(BaseModel):
    job_id: str
    project_id: str
    step: PipelineStep
    progress: float = 0.0
    message: str = ""
    error: Optional[str] = None


class ProjectResponse(BaseModel):
    project_id: str
    topic: str
    status: PipelineStep
    script: Optional[ScriptSchema] = None
    scene_plans: Optional[List[ScenePlanSchema]] = None
    voice_files: Optional[List[str]] = None
    video_url: Optional[str] = None
    render_manifest_path: Optional[str] = None
    job: Optional[JobStatus] = None
    config: Optional[Dict[str, Any]] = None
    ai_sketch_audit: Optional[List[Dict[str, Any]]] = None
    ai_image_audit: Optional[List[Dict[str, Any]]] = None
    # Voice provider status fields
    voice_generation_status: Optional[str] = None    # pending | completed
    f5_package_exported: Optional[bool] = None        # True once narration pack has been exported
    f5_processing_status: Optional[str] = None       # queued | processing | audio_ready | completed | failed
    # F5 import audit fields
    audio_imported_at: Optional[str] = None           # ISO-8601 timestamp of last voice import
    # Avatar pipeline metadata (Phase-4 SadTalker)
    avatar_provider: Optional[str] = None             # null | sadtalker | liveportrait | musetalk
    avatar_source: Optional[str] = None               # path to reference source image
    avatar_status: Optional[str] = None               # null | sadtalker | liveportrait | musetalk
    avatar_generation_status: Optional[str] = None    # pending | completed
    sadtalker_package_exported: Optional[bool] = None  # True once avatar pack has been exported
    sadtalker_processing_status: Optional[str] = None  # queued | processing | clips_ready | completed | failed
    avatar_imported_at: Optional[str] = None           # ISO-8601 timestamp of last clip import
    avatar_position: Optional[str] = None              # bottom_right | bottom_left | bottom_center
    avatar_scale: Optional[float] = None               # 0.0–1.0 relative to video height
